== Data Domains Details

The Data Domains described above are implemented using multiple models and other resources. The following subsections describe the Domains' details and link to all their resources.

=== Data Cataloguing Domain

=== Organisations & People Domain

=== Sampling Domain

* **GA Sampling Profile**
** https://surroundaustralia.github.io/ga-supermodel/ga-sampling.html
** A profile of several ontologies and a Semantic Web implementation of the Sampling Features Schema described in clauses 9-11 of <<ISO19156>>
** This ontology directly inherits from the _SAM Lite ontology_ <<SAM>>, the _SOSA_ ontology <<SOSA>> and the _TERN Ontology_ <<TERN>>
** It is concerned only with characterising physical samples

* **_Semantic Sensor Networks_ ontology**
** https://www.w3.org/TR/vocab-ssn/
** A https://www.w3.org/:[W3C] "recommendation" (standard) ontology, <<SSN>>
** The Domain Main Classes for the _Sampling_ domain are all SOSA Ontology classes. SOSA is a component ontology of the SSN Ontology

* **SAM Lite ontology**
** https://surroundaustralia.github.io/ga-supermodel/sam-lite.html
** A Semantic Web implementation of the Sampling Features Schema described in clauses 9-11 of <<ISO19156>>
** This ontology is no longer in direct use but is the foundation for the _GA Samples Ontology_

* **GA's _Samples_ API online**
** http://pid.geoscience.gov.au/sample/
** This API provides access to multiple model representations of the metadata of Geosceicne Australia's samples dataset

* **Example sample data: AU128**
** https://github.com/surroundaustralia/ga-supermodel/blob/main/domain-models/samples/AU128.sosa.ttl[SOSA Modelling]
** https://github.com/surroundaustralia/ga-supermodel/blob/main/domain-models/samples/AU128.sam.ttl[SAM Modelling]
** https://github.com/surroundaustralia/ga-supermodel/blob/main/domain-models/samples/AU128.prov.ttl[PROV Modelling]

=== Spatiality Domain

=== Theming Domain
