name: Auto-buid HTML

on: 
  push: 
      branches:
          - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      working-directory: ./
      run: |
        echo "Making deployment dir - docs/"
        mkdir docs
        echo "Add README to docs/"
        cp README.md docs/        
        sudo apt-get install asciidoctor ruby -y
        echo "Add supermodel to docs/"
        asciidoctor supermodel.adoc -o docs/index.html
        sed -i 's#img src="#img src="https://surroundaustralia.github.io/ga-supermodel/#' docs/index.html        
        echo "Add supermodel RDF to docs/"
        cp supermodel.ttl docs/             
        echo "Add images to docs/"
        cp -r img docs/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: docs